server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://127.0.0.1:8100
          predicates:
            - Path=/api/auth/**
        - id: auth-service-admin
          uri: http://127.0.0.1:8100
          predicates:
            - Path=/api/admin/users/**,/api/admin/roles/**,/api/admin/permissions/**
        - id: content-service
          uri: http://127.0.0.1:8101
          predicates:
            - Path=/api/admin/tag-types/**,/api/admin/tags/**,/api/admin/adverts/**,/api/admin/banners/**
        - id: user-service
          uri: http://127.0.0.1:8102
          predicates:
            - Path=/api/admin/customers/**,/api/admin/customer-exps/**,/api/admin/customer-blacklist/**
        - id: legacy-php
          uri: http://localhost:8001
          predicates:
            - Path=/legacy-php/**
          filters:
            - StripPrefix=1
