apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: gacha-system
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 8100
      targetPort: 8100
      protocol: TCP
      name: http
  selector:
    app: auth-service
