server:
  port: 8101

spring:
  application:
    name: content-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/content_svc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/content-svc-changelog.xml
    enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deletedAt
      logic-delete-value: now()
      logic-not-delete-value: "NULL"

knife4j:
  enable: true
  setting:
    language: zh_cn
