apiVersion: v1
kind: Secret
metadata:
  name: gacha-credentials
  namespace: gacha-system
type: Opaque
stringData:
  mysql-root-password: "admin123"
  mysql-username: "root"
  redis-password: ""
  jwt-private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    CHANGE_ME: generate with: openssl genrsa -out private.pem 2048
    -----END RSA PRIVATE KEY-----
  jwt-public-key: |
    -----BEGIN PUBLIC KEY-----
    CHANGE_ME: generate with: openssl rsa -in private.pem -pubout -out public.pem
    -----END PUBLIC KEY-----
